### ISSUE TITLE
QuestStrategy.Execute does not execute as expected

### ISSUE THREAD

**Issue by shottah** [rodit/RBot#2]
## Expected Functionality
1. Accepts Quest
2. Executes Routines for Item Requirements
3. Submits Quest for Item
4. Repeat if necessary

## What does it  currently do?
1. Loads Quest Dialogue

Given the limitation of the implementation I went ahead and attempted this without any luck.
```cs
while (!bot.Inventory.Contains("Unidentified 19", 1)) {
			drop.RegisterDrop("escherion", "Escherion|Staff of Inversion", "Escherion's Helm");
			drop.Obtain("Escherion's Helm", 1);
			rewards.RegisterQuest(555);
			rewards.Obtain("Unidentified 19", 1);
		}
```

**Comment by matabeitt** [comment]
This issue blocks #1
